### ISSUE TITLE
There's a problem to follow mecha-docs.

### ISSUE THREAD

**Issue by kahn3015** [mechaphish/mecha-docs#3]
I try to setup mechaphish.

So, I try to follow mecha-docs.

On setting up DB, there's an error.
workon cgc
cd farnsworth
cp .env.example .env
./setupdb.sh

(cgc) root@john-SVP1322XPKB:/home/john/angr-dev/farnsworth# ./setupdb.sh 
[*] dropdb -U postgres -h localhost -p 5432 --if-exists farnsworth
[*] createdb -U postgres -h localhost -p 5432 farnsworth
Traceback (most recent call last):
  File "/root/.virtualenvs/cgc/bin/farnsworth", line 11, in <module>
    load_entry_point('farnsworth', 'console_scripts', 'farnsworth')()
  File "/root/.virtualenvs/cgc/lib/python3.5/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/root/.virtualenvs/cgc/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/root/.virtualenvs/cgc/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/root/.virtualenvs/cgc/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/john/angr-dev/farnsworth/farnsworth/__init__.py", line 8, in <module>
    from .config import master_db
  File "/home/john/angr-dev/farnsworth/farnsworth/config.py", line 32
    except (peewee.OperationalError, peewee.InterfaceError), error:

It seems to a problem about python version.
farnsworth is for python3 however config.py is for python2.
I can't fix this problem.
Do shall I do?

**Comment by buckohfive** [comment]
Farnsworth is entirely python2.  It should be ported to python3.  I ran it through 2to3, but there are other conversions necessary - for example, converting instances of string.letters to string.ascii_letters.

I found a much lazier solution was to modify /home/{user}/.virtualenvs/cgc/bin/farnsworth to call python2 instead.  Change the initial #! from python3 to /usr/bin/which python2 (or point it to a specific binary if you like).

This worked on Ubuntu 16.04.5

Also, meister will need to be similarly modified.

However, the DARPA VMs are no longer available.  Does anyone have a backup?

**Comment by zardus** [comment]
Unfortunately, this whole project is here mostly for archival purposes. We have some other stuff in the mix as a replacement, but nothing really ready yet.

**Comment by buckohfive** [comment]
Fysa I'm working with Ian Crone at DARPA to get them reinstated.

Mike

**Comment by ljian236** [comment]
The same error happens to me. I worked on Ubuntu 18.04. 
Let me know how to resolve it. Thanks!
